// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_application_1/test/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_application_1/core/result.dart' as _i4;
import 'package:flutter_application_1/models/models.dart' as _i5;
import 'package:flutter_application_1/repositories/auth_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  @override
  _i3.Future<_i4.Result<_i5.User>> login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            username,
            password,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.User>>.value(
            _i6.dummyValue<_i4.Result<_i5.User>>(
          this,
          Invocation.method(
            #login,
            [
              username,
              password,
            ],
          ),
        )),
        returnValueForMissingStub: _i3.Future<_i4.Result<_i5.User>>.value(
            _i6.dummyValue<_i4.Result<_i5.User>>(
          this,
          Invocation.method(
            #login,
            [
              username,
              password,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.User>>);

  @override
  _i3.Future<_i4.Result<void>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i5.User?> getPersistedUser() => (super.noSuchMethod(
        Invocation.method(
          #getPersistedUser,
          [],
        ),
        returnValue: _i3.Future<_i5.User?>.value(),
        returnValueForMissingStub: _i3.Future<_i5.User?>.value(),
      ) as _i3.Future<_i5.User?>);

  @override
  _i3.Future<void> persistUser(_i5.User? user) => (super.noSuchMethod(
        Invocation.method(
          #persistUser,
          [user],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearPersistedUser() => (super.noSuchMethod(
        Invocation.method(
          #clearPersistedUser,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
